-- Pre-fill Fran's recipe collection
-- ingredients = jsonb, tags = text[]
DO $$
DECLARE fran_id uuid;
BEGIN
  SELECT id INTO fran_id FROM auth.users WHERE email = 'fmach002@gmail.com';
  IF fran_id IS NULL THEN RAISE EXCEPTION 'User not found'; END IF;

  INSERT INTO recipes (profile_id, name, ingredients, instructions, tags) VALUES
  (fran_id, 'Chana Masala', '["2 tbsp oil","1 tbsp garlic","1 tbsp ginger","1/2 onion diced","2 serranos","1 tsp cumin seeds","1/4 tsp turmeric","1/2 tsp ground coriander","1 tsp Kashmiri chili powder","4 Roma tomatoes diced or can diced tomatoes drained","1 tsp salt","2 cans chickpeas drained","1 1/2 cups chicken stock","1 tsp garam masala","2 tbsp cilantro","Kale"]'::jsonb, 'Heat oil on low. Stir in garlic, ginger, onion, serranos. Cook 5 min. Stir in cumin, turmeric, coriander, chile powder, salt. Add tomatoes. Medium heat 5 min. Stir in chickpeas and stock. Boil, reduce, simmer 5 min. Sprinkle garam masala and cilantro.', ARRAY['curry','indian','vegetarian']),
  (fran_id, 'Yellow Potato Curry', '["2 large or 4 small potatoes","Oil","1/2 onion finely chopped","Mustard seeds","Cumin seeds","Fennel seeds","Fenugreek seeds","Turmeric powder","2 green chilies or red dry chilies","Salt"]'::jsonb, 'Peel and cube potatoes. Microwave in ziplock with water 4-5 min. Heat oil, add mustard, fennel, cumin, fenugreek seeds. Add onions and chilies. Add 1 tsp turmeric. Add potatoes and salt. Add water, stir, simmer until evaporated.', ARRAY['curry','indian','vegetarian','potato']),
  (fran_id, 'Green Bean Curry', '["1 packet frozen French-cut green beans","1/2 small yellow onion finely chopped","2-3 tbsp oil","1/4 tsp cumin seeds","1/4 tsp mustard seeds","1/4 tsp fennel seeds","1/4 tsp fenugreek seeds","1 tbsp masala","1 tsp turmeric","1 green chili halved","1 tomato finely chopped","Salt","Cilantro"]'::jsonb, 'Heat oil. Add seeds. Add onions and chili until soft. Add turmeric and masala. Add beans and salt. Add water, simmer. Create well, add tomato and cilantro. Simmer until soft, mix in.', ARRAY['curry','indian','vegetarian']),
  (fran_id, 'Lamb Curry', '["2 lbs lamb cubed","1 onion sliced","2 bay leaves","1 tsp fennel seeds","2 serranos halved","Cinnamon stick","2 tsp ginger garlic","1 tsp turmeric","3 tbsp masala","1 can diced tomatoes","3 potatoes quartered","2 cups water","2 tbsp salt","1 cup peas","Cilantro"]'::jsonb, 'Heat oil, add onions, bay leaves, fennel, serranos, cinnamon. Cook 5 min. Add ginger/garlic, turmeric, masala 5 min. Brown meat 5-10 min. Add tomatoes, potatoes, water, salt. Cover 20 min. Add peas 10 min. Cilantro.', ARRAY['curry','indian','lamb','meat']),
  (fran_id, 'Steak Curry', '["2 lbs sirloin cubed","1 onion diced","2 bay leaves","1 tsp fennel seeds","2 serranos halved","Cinnamon stick","2 tsp ginger garlic","1 tsp turmeric","2 tbsp masala","1 cup water","2 tbsp salt","1 can diced tomatoes","1 can butter beans","Cilantro"]'::jsonb, 'Heat oil, add onions, bay leaves, fennel, serranos, cinnamon. Cook 5 min. Add ginger/garlic, turmeric, masala 5 min. Brown meat 5-10 min. Add tomatoes, water, salt. Cover 20 min. Add beans 10 min. Cilantro. Serve with carrot salad.', ARRAY['curry','indian','steak','meat']),
  (fran_id, 'Chicken Curry', '["1 whole chicken or breast with bones and boneless thighs","3 tbsp olive oil","3 cardamom pods","1 cinnamon stick","4 cloves","1 serrano split","1/2 onion diced","4 garlic cloves crushed","1 tsp ginger","1 tsp coriander","1 tsp cumin","1 tsp chili powder","1 tsp turmeric","2 tsp salt","2 tomatoes","1 1/2 cups water","2 russet potatoes chunked","1 tbsp cilantro"]'::jsonb, 'Season chicken with salt, garlic, ginger. Brown in oil, set aside. Fry cardamom, cinnamon, cloves, onions, garlic, ginger, spices 10 min. Add tomatoes, water, potatoes 10 min. Add chicken and cilantro 10 min.', ARRAY['curry','indian','chicken','meat']),
  (fran_id, 'Mince Curry', '["2 tbsp olive oil","1/2 onion diced","1/2 tsp masala","1/2 tsp turmeric","Star anise/fennel seed","Bay leaf","2 tomatoes diced","2 large potatoes diced","1 1/2 cups water","1 cup peas","Garlic","Salt and pepper","Cilantro"]'::jsonb, 'Heat oil, add onions, masala, turmeric, star anise, bay leaf. Add tomatoes and potatoes. Add water. Marinate protein with garlic, s&p, add to pot. Cover 30 min. Cilantro.', ARRAY['curry','indian','quick','meat']),
  (fran_id, 'Aloo Gobi', '["2 tbsp evoo","3 Yukon potatoes quartered","1 head cauliflower chunked","1 tbsp garlic","2 tomatoes diced","1/2 onion chopped","2 tbsp cilantro","1 tsp masala","1/2 tsp turmeric","2 tsp salt","1 tsp pepper","1 1/2 cups water","1/2 cup peas"]'::jsonb, 'Boil potatoes 10 min, drain. Roast cauliflower at 400F 20 min. Heat pot, add evoo, onion, garlic 5 min. Add tomatoes and spices 5 min. Add water, cauliflower, potatoes, cover 10 min. Add peas and cilantro, no lid, 10 min.', ARRAY['curry','indian','vegetarian','potato']),
  (fran_id, 'Fish Curry', '["1 tbsp ginger","2 tbsp olive oil","1 onion diced","4-6 garlic cloves","Serrano optional","1 tsp masala","1/2 tsp turmeric","Mustard seed","Cumin seeds","Bay leaf","Curry leaves","2 cans tomatoes","1 tbsp tamarind paste","1/2 cup water","1 lb fish","Cilantro"]'::jsonb, 'Heat oil, add onion, garlic, ginger, serrano. Add spices and seeds. Add tomatoes and tamarind with water. Immersion blender. Add fish. Cover 20-30 min. Cilantro.', ARRAY['curry','indian','fish','seafood']),
  (fran_id, 'Lamb Chop Chutney', '["1 lb lamb chops","2 tbsp olive oil","1 onion roughly chopped","2 cans diced tomatoes","1 tsp masala","1/2 tsp turmeric","Curry leaves","Ginger","Garlic","Salt and pepper"]'::jsonb, 'Season chops with ginger, garlic, s&p. Brown each side 5 min, set aside. Heat oil, add onion 5 min. Add masala, turmeric, curry leaves, s&p. Add tomatoes 5 min. Cover 10 min. Blend. Add chops 10 min.', ARRAY['curry','indian','lamb','chutney']),
  (fran_id, 'Carrot Salad', '["Cucumber thinly sliced","1 onion diced","3 chilies optional","4 radishes thinly sliced","Romaine lettuce","4 carrots","Lemon juice"]'::jsonb, 'Grate carrots. Cube cucumber. Thin slice onion. Slice radishes. Slice romaine fine. Combine carrots, cucumbers, onions with lemon juice. Add radish and lettuce when serving.', ARRAY['salad','side','indian']),
  (fran_id, 'Sambals', '["Diced tomatoes","Diced onions","Diced cucumbers","Lime juice","Salt and pepper"]'::jsonb, 'Dice tomatoes, onions, cucumbers. Combine with lime juice, salt and pepper.', ARRAY['condiment','side','indian','quick']),
  (fran_id, 'Baked Beans', '["Serrano pepper","1/2 onion diced","1 tsp masala","1 tsp turmeric","1 can baked beans","1 can tomatoes","Oil","Salt and pepper"]'::jsonb, 'Heat oil, add onions, serrano, masala, turmeric 5-10 min. Add tomatoes and beans, simmer 20 min. Salt and pepper.', ARRAY['side','indian','quick','vegetarian']),
  (fran_id, 'Egg Chutney', '["4 eggs","1-2 tbsp olive oil","1/2 onion diced","1 serrano halved","1 28oz can crushed tomatoes","1/2 tsp masala","1/2 tsp turmeric","Salt and pepper"]'::jsonb, 'Heat oil, add onions, masala, turmeric 5-10 min. Add tomatoes until warm. Add eggs one by one on top. S&p. Cover 5-7 min.', ARRAY['indian','eggs','quick']),
  (fran_id, 'Tandoori', '["Meat of choice","Garlic","Ginger","Lemon juice","Salt","1/2 cup yogurt","1 tbsp paprika","1 tsp Kashmiri chile","1 tsp garam masala","1 tsp cumin","1/2 tsp cardamom"]'::jsonb, 'Season meat with garlic, ginger, lemon, salt. Mix yogurt with spices into paste. Coat meat for a couple hours. Oven 400F, roast 20-30 min.', ARRAY['indian','tandoori','meat']),
  (fran_id, 'Masala Fish', '["Fish","Cumin/coriander mix","Minced garlic","Mint/pani puri mix","Turmeric","Lemon juice","Salt"]'::jsonb, 'Mix spices with garlic, lemon juice into paste. Salt. Coat fish. Fry 4-5 min, flip, fry 4-5 min.', ARRAY['indian','fish','seafood','quick']);
END $$;
